CREATE DATABASE bdCuboMagico
GO

USE bdCuboMagico
GO

CREATE TABLE Cliente(
CODIGO INT IDENTITY PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
SEXO VARCHAR(15) NOT NULL,
DATA_NASCIMENTO VARCHAR(11) NOT NULL,
CPF VARCHAR(16) NOT NULL,
ESTADO_CIVIL VARCHAR(30) NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(15),
CELULAR VARCHAR(16) NOT NULL,
CEP VARCHAR(11) NOT NULL,
ENDERECO VARCHAR(50) NOT NULL,
NUMERO VARCHAR(13) NOT NULL,
ESTADO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(40) NOT NULL,
BAIRRO VARCHAR(50) NOT NULL,
COMPLEMENTO VARCHAR(100),
REFERENCIA VARCHAR(100),
GENERO1 VARCHAR(30),
GENERO2 VARCHAR(30),
GENERO3 VARCHAR(30),
GENERO4 VARCHAR(30),
GENERO5 VARCHAR(30),
)
GO

CREATE TABLE Fornecedor(
CODIGO INT IDENTITY  PRIMARY KEY ,
NOME_FANTASIA VARCHAR(100) NOT NULL,
RAZAO_SOCIAL VARCHAR(100) NOT NULL,
CATALOGO VARCHAR(100),
EMAIL VARCHAR(100),
TELEFONE VARCHAR(15) NOT NULL,
CNPJ VARCHAR(100) NOT NULL,
PAIS VARCHAR(100) NULL,
)

GO

CREATE TABLE Funcionarios(
CODIGO int IDENTITY PRIMARY KEY ,
NOME VARCHAR(100) NOT NULL,
SEXO VARCHAR(15) NOT NULL,
DATA_NASCIMENTO VARCHAR(11) NOT NULL,
CPF VARCHAR(16) NOT NULL,
CARGO VARCHAR(30) NOT NULL,
ESTADO_CIVIL VARCHAR(30) NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(15) NULL,
CELULAR VARCHAR(16) NOT NULL,
CEP VARCHAR(11) NOT NULL,
ENDERECO VARCHAR(50) NOT NULL,
NUMERO VARCHAR(13) NOT NULL,
ESTADO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(40) NOT NULL,
BAIRRO VARCHAR(50),
COMPLEMENTO VARCHAR(100),
REFERENCIA VARCHAR(100)
) 
GO

CREATE TABLE Usuario(
CODIGO INT IDENTITY PRIMARY KEY,
CodFunc INT REFERENCES Funcionarios,
USUARIO VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL
)
GO


CREATE TABLE TipoAcesso(
CodUsuario INT REFERENCES Usuario,
CARGO VARCHAR(20) NOT NULL,
)
GO

CREATE TABLE Editora(
CODIGO INT IDENTITY PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
CNPJ VARCHAR(20) UNIQUE NOT NULL,
PAIS VARCHAR(30)
)
GO

CREATE TABLE Livro(
CODIGO INT IDENTITY PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
QUANTIDADE INT NOT NULL,
CAPA VARCHAR(100),
SINOPSE VARCHAR(1000),
AUTOR VARCHAR(50),
EDITORA INT REFERENCES Editora,
GENERO VARCHAR(50) NOT NULL,
DATA_PUBLICACAO VARCHAR(11),
QTD_PAGINAS INT,
VALOR DECIMAL(6,2)
)
GO

CREATE TABLE Produto(
CODIGO INT IDENTITY PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
QUANTIDADE INT NOT NULL,
DESCRICAO VARCHAR(50),
VALOR DECIMAL(6,2) NOT NULL
)
GO

CREATE TABLE EstoqueLivro (
COD_LIVRO INT IDENTITY FOREIGN KEY REFERENCES Livro,
NOME VARCHAR (100) NOT NULL,
QUANTIDADE INT NOT NULL,
GENERO VARCHAR(50),
PRECO DECIMAL(6,2) NOT NULL
)
GO

CREATE TABLE EstoqueProduto (
COD_LIVRO INT IDENTITY FOREIGN KEY REFERENCES Produto,
NOME VARCHAR (100) NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO DECIMAL(6,2) NOT NULL
)
GO

CREATE TABLE USER_LIVROS_SORTEADOS(
ID_USER VARCHAR (5),
ID_LIVRO VARCHAR (5)
)
GO